---
title: javascript 异步 获取返回值
date: 2017-03-20 08:16:38
tags:
---

---
场景：获取fn函数中的返回值
问题：由于异步的原因，不能获得预期中的返回值
```javascript
function fn() {
    let a = 0;
    setTimeout(() => {
        a = 2;
    }, 100);
    return a; //预期返回2
}
console.log(fn()); //0
```
---
### callback
返回值只能在fn2中正确获取
```javascript
function fn(callback) {
    let a = 0;
    setTimeout(() => {
        a = 2;
        callback(2);
    } ,100);
}
function fn2(value) {
    console.log(value); //2 后输出
    return value;
}
const x = fn(fn2);
console.log(x); //0  先输出
```
---
### promise
promise任何操作都会返回一个promise对象
返回的promise对象有三种状态
> unfulfilled 初始状态 未完成
> fulfilled 已完成
> failed 失败

```javascript
function fn() {
    let a = 0;
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            a = 2;
            resolve(a);
        }, 100);
    });
}
function fn2(value) {
    console.log(value); //2
    return value;
}
fn().then(fn2);
//-----------------------
const myPromise = new Promise((resolve, reject) => {
    let a = 0;
    setTimeout(() => {
        a = 2;
        resolve(a);
    }, 100);
});
myPromise.then((value) => console.log(value)); //2
```
---
### generator
```javascript
function fn() {
    let a = 0;
    setTimeout(() => {
        a = 2;
        it.next(a);
    }, 100);
}
function *fn2 (it) {
    let x = yield fn();
    console.log(x); //2
}
const it = fn2();
it.next();
```
---
### async
```javascript
function fn() {
    let a = 0;
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            a = 2;
            resolve(a);
        }, 100);
    });
}
const fn2 = async () => {
    const x = await fn();
    console.log(x);
};
fn2();
```
